---
services:
  postgres:
    image: postgres:15
    container_name: o11y_postgres
    environment:
      POSTGRES_DB: o11y
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
